/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kr_ac_snu_hcil_customkeyboard_WordCorrector */

#ifndef _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector
#define _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    correctWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_correctWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    setContext
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_setContext
  (JNIEnv *, jobject, jstring);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    clearSentence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_clearSentence
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    decodeKey
 * Signature: (C)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_decodeKey
  (JNIEnv *, jobject, jchar);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    decodeTouchKey
 * Signature: (FF)Lkr/ac/snu/hcil/customkeyboard/WordCorrector/TouchString;
 */
JNIEXPORT jobject JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_decodeTouchKey
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    decodeWord
 * Signature: ()[Lkr/ac/snu/hcil/customkeyboard/WordCorrector/PredictEntry;
 */
JNIEXPORT jobjectArray JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_decodeWord
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    decodeSentence
 * Signature: ()[Lkr/ac/snu/hcil/customkeyboard/WordCorrector/PredictEntry;
 */
JNIEXPORT jobjectArray JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_decodeSentence
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    backKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_backKey
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    backWord
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_backWord
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    init
 * Signature: (Lkr/ac/snu/hcil/customkeyboard/WordCorrector/Configuration;)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    predictChar
 * Signature: (IF)[Lkr/ac/snu/hcil/customkeyboard/WordCorrector/PredictEntry;
 */
JNIEXPORT jobjectArray JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_predictChar
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    predictWord
 * Signature: (IF)[Lkr/ac/snu/hcil/customkeyboard/WordCorrector/PredictEntry;
 */
JNIEXPORT jobjectArray JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_predictWord__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    predictWord
 * Signature: (IFC)[Lkr/ac/snu/hcil/customkeyboard/WordCorrector/PredictEntry;
 */
JNIEXPORT jobjectArray JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_predictWord__IFC
  (JNIEnv *, jobject, jint, jfloat, jchar);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    pushWord
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_pushWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     kr_ac_snu_hcil_customkeyboard_WordCorrector
 * Method:    getChar
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_kr_ac_snu_hcil_customkeyboard_WordCorrector_getChar
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class kr_ac_snu_hcil_customkeyboard_WordCorrector_ConfBuilder */

#ifndef _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_ConfBuilder
#define _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_ConfBuilder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class kr_ac_snu_hcil_customkeyboard_WordCorrector_ConfBuilder_FingerType */

#ifndef _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_ConfBuilder_FingerType
#define _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_ConfBuilder_FingerType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class kr_ac_snu_hcil_customkeyboard_WordCorrector_Configuration */

#ifndef _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_Configuration
#define _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_Configuration
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class kr_ac_snu_hcil_customkeyboard_WordCorrector_PredictEntry */

#ifndef _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_PredictEntry
#define _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_PredictEntry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class kr_ac_snu_hcil_customkeyboard_WordCorrector_TouchString */

#ifndef _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_TouchString
#define _Included_kr_ac_snu_hcil_customkeyboard_WordCorrector_TouchString
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
